[package]
name = "simple_line_notify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12"
tokio = { version = "1.37", features = ["full"] }
dotenv = { version = "0.15" }